# -*- encoding: utf-8 -*-

"""
Copyright (c) 2019 - present AppSeed.us
"""

import pytest
import json

from api import app

import random
import string

"""
   Sample test data
"""

# TEST CASE #1: current dummy usersname should be able to do it
# TEST CASE #2: allows autogenerated usernames and emails and passwords to be created
DUMMY_USERNAME = "apple"
DUMMY_EMAIL = "apple@apple.com"
DUMMY_PASS = "newpassword"

def generateDummyData():
    DUMMY_USERNAME = ''.join(random.choices(string.ascii_lowercase, k=5))
    DUMMY_EMAIL = DUMMY_USERNAME + "@apple.com"
    DUMMY_PASS = ''.join(random.choices(string.ascii_lowercase, k=11))
    return DUMMY_USERNAME, DUMMY_EMAIL, DUMMY_PASS




@pytest.fixture
def client():
    with app.test_client() as client:
        yield client

def test_user_signup(client):
    """
       Tests /users/register API
    """
    DUMMY_USERNAME, DUMMY_EMAIL, DUMMY_PASS = generateDummyData()
    print("generated: ",{
                "username": DUMMY_USERNAME,
                "email": DUMMY_EMAIL,
                "password": DUMMY_PASS
            } )
    response = client.post(
        "api/users/register",
        data=json.dumps(
            {
                "username": DUMMY_USERNAME,
                "email": DUMMY_EMAIL,
                "password": DUMMY_PASS
            }
        ),
        content_type="application/json")

    print("The user was successfully registered")
    data = json.loads(response.data.decode())
    print("RESULT:", data)
    assert response.status_code == 200
    assert "The user was successfully registered" in data["msg"]
    
def test_user_signup_duplicate(client):
    """
       Tests /users/register API
    """
    DUMMY_USERNAME, DUMMY_EMAIL, DUMMY_PASS = generateDummyData()
    print("generated: ",{
                "username": DUMMY_USERNAME,
                "email": DUMMY_EMAIL,
                "password": DUMMY_PASS
            } )
    response = client.post(
        "api/users/register",
        data=json.dumps(
            {
                "username": DUMMY_USERNAME,
                "email": DUMMY_EMAIL,
                "password": DUMMY_PASS
            }
        ),
        content_type="application/json")

    responseDuplicate = client.post(
        "api/users/register",
        data=json.dumps(
            {
                "username": DUMMY_USERNAME,
                "email": DUMMY_EMAIL,
                "password": DUMMY_PASS
            }
        ),
        content_type="application/json")

    # print("The user was successfully registered")
    data = json.loads(response.data.decode())
    print("RESULT:", data)
    assert responseDuplicate.status_code == 400
    assert "The user was successfully registered" in data["msg"]
    


def test_user_signup_invalid_data(client):
    """
       Tests /users/register API: invalid data like email field empty
    """
    print("test_user_signup_invalid_data")
    response = client.post(
        "api/users/register",
        data=json.dumps(
            {
                "username": DUMMY_USERNAME,
                "email": "",
                "password": DUMMY_PASS
            }
        ),
        content_type="application/json")

    data = json.loads(response.data.decode())
    assert response.status_code == 400
    assert "'' is too short" in data["msg"]


def test_user_login_correct(client):
    """
       Tests /users/signup API: Correct credentials
    """
    print("test_user_login_correct")
    response = client.post(
        "api/users/login",
        data=json.dumps(
            {
                "email": DUMMY_EMAIL,
                "password": DUMMY_PASS
            }
        ),
        content_type="application/json")

    data = json.loads(response.data.decode())
    assert response.status_code == 200
    assert data["token"] != ""


def test_user_login_error(client):
    """
       Tests /users/signup API: Wrong credentials
    """
    print("test_user_login_error")
    response = client.post(
        "api/users/login",
        data=json.dumps(
            {
                "email": DUMMY_EMAIL,
                "password": DUMMY_EMAIL
            }
        ),
        content_type="application/json")

    data = json.loads(response.data.decode())
    assert response.status_code == 400
    assert "Wrong credentials." in data["msg"]
